apiVersion: v2
appVersion: 7.35.2
dependencies:
  - name: postgresql
    version: 10.3.18
    repository: https://charts.jfrog.io/
    condition: postgresql.enabled
  - name: rabbitmq
    version: 8.11.4
    repository: https://charts.jfrog.io/
    condition: rabbitmq.enabled
  - name: redis
    version: 12.10.1
    repository: https://charts.jfrog.io/
    condition: redis.enabled
  - name: artifactory
    version: 107.35.2
    repository: https://charts.jfrog.io/
    condition: artifactory.enabled
  - name: xray
    version: 103.44.1
    repository: https://charts.jfrog.io/
    condition: xray.enabled
  - name: distribution
    version: 102.12.1
    repository: https://charts.jfrog.io/
    condition: distribution.enabled
  - name: insight
    version: 101.7.0
    repository: https://charts.jfrog.io/
    condition: insight.enabled
  - name: pipelines
    version: 101.21.5
    repository: https://charts.jfrog.io/
    condition: pipelines.enabled
description: The Helm chart for JFrog Platform (Universal, hybrid, end-to-end DevOps automation)
home: https://jfrog.com/platform/
icon: https://raw.githubusercontent.com/jfrog/charts/master/stable/jfrog-platform/logo/jfrog-platform-logo.png
keywords:
- platform
- artifactory
- jfrog
- devops
maintainers:
- email: installers@jfrog.com
  name: Chart Maintainers at JFrog
name: jfrog-platform
sources:
- https://github.com/jfrog/charts
type: application
version: 10.4.0
kubeVersion: ">= 1.14.0-0"
